chef:
  server:
    install_script: https://raw.github.com/rcbops/jenkins-build/master/qa/bash/jenkins/install-chef-server.sh
    install_dir: /opt/rcbops
  run_cmd: "chef-client"
razor:
  ip: 198.101.133.3
environments:
    openssh:
      server:
        subsystem: "sftp internal-sftp"
    package_component:
        default: grizzly
    keystone:
        default:
            admin_user: admin
            users:
                demo:
                    roles:
                        Member:
                          - demo
                    default_tenant: demo
                    password: secrete
                demo2:
                    roles:
                        Member:
                          - demo2
                    default_tenant: demo2
                    password: secrete
                admin:
                    roles:
                        admin:
                            - admin
                            - demo
                    password: secrete
            tenants:
                - admin
                - service
                - demo
                - demo2
        ldap:
            debug: True
            auth_type: ldap
            ldap:
                user_mail_attribute: mail
                user_enabled_emulation: True
                user_tree_dn: "ou=Users,dc=rcb,dc=me"
                user_attribute_ignore: tenantId
                tenant_enabled_emulation: True
                url: ldap://<LDAP_IP>
                user: "cn=admin,dc=rcb,dc=me"
                role_objectclass: organizationalRole
                tenant_objectclass: groupOfNames
                group_attribute_ignore: enabled
                tenant_attribute_ignore: tenantId
                tenant_tree_dn: "ou=Groups,dc=rcb,dc=me"
                allow_subtree_delete: false
                password: <LDAP_ADMIN_PASS>
                suffix: "dc=rcb,dc=me"
                user_objectclass: inetOrgPerson
                domain_attribute_ignore: enabled
                use_dumb_member: True
                role_tree_dn: "ou=Roles,dc=rcb,dc=me"
            admin_user: admin
            users:
                demo:
                    roles:
                        Member:
                            - demo
                        default_tenant: demo
                        password: secrete
                admin:
                   roles:
                        admin:
                            - admin
                            - demo
                   password: secrete
            tenants:
                - admin
                - service
                - demo
                - demo2
        swift:
           swift_admin_url: ""
           swift_public_url: ""
           swift_internal_url: ""
           auth_password: "secrete"
           admin_password: "secrete"
           ops_password: "secrete"
    monitoring:
        default:
            metric_provider: collectd
            procmon_provider: monit
    mysql:
        default:
            root_network_acl: "%"
            allow_remote_root: true
    nova:
        razor:
            apply_patches: false
            networks:
                public:
                    bridge: br0
                    dns1: 8.8.8.8
                    dns2: 8.8.4.4
                    bridge_dev: eth1
                    network_size: "254"
                    ipv4_cidr: 172.31.0.0/24
                    label: public
            libvirt:
                virt_type: kvm
        rackspace:
          apply_patches: false
          networks:
              public:
                  bridge: br0
                  dns1: 8.8.8.8
                  dns2: 8.8.4.4
                  bridge_dev: eth1
                  network_size: "254"
                  ipv4_cidr: 172.31.0.0/24
                  label: public
          libvirt:
            virt_type: qemu
    osops:
        default:
            apply_patches: true
    horizon:
        default:
            theme: default
    developer_mode:
        default:
            default: false
    osops_networks:
      razor:
        management: 198.101.133.0/24
        nova: 198.101.133.0/24
        public: 198.101.133.0/24
      rackspace:
        management: 10.0.0.0/8
        nova: 10.0.0.0/8
        public: 192.237.0.0/16
    glance:
        default:
            image_upload: true
            images:
                - cirros
                - precise
        cf:
            api:
                default_store: swift
                swift_store_user: <Tenant_Id>:<Tenant_Name>
                swift_store_key: <Tenant_Password>
                swift_store_auth_version: "2"
                swift_store_auth_address: https://identity.api.rackspacecloud.com/v2.0
                swift_store_region: DFW
            image_upload: true
            images:
                - cirros
                - precise
    neutron:
        quantum:
            ovs:
                network_type: gre
        neutron:
            ovs:
                network_type: gre
    cinder:
        local:
            storage:
                lvm:
                    volume_group: vgubuntu01
    swift:
        rpcs:
            swift-private-cloud:
                network:
                    management: 198.101.133.0/24
                    exnet: 198.101.133.0/24
                swift_common:
                   swift_hash_prefix: secretesecretestring
                   swift_hash_suffix: ""
                dispersion:
                    dis_key: secrete
    vips:
        precise:
            mysql-db: 198.101.133.154
            rabbitmq-queue: 198.101.133.155
            cinder-api: 198.101.133.156
            glance-api: 198.101.133.156
            glance-registry: 198.101.133.156
            horizon-dash: 198.101.133.156
            horizon-dash_ssl: 198.101.133.156
            keystone-admin-api: 198.101.133.156
            keystone-internal-api: 198.101.133.156
            keystone-service-api: 198.101.133.156
            nova-api: 198.101.133.156
            nova-ec2-public: 198.101.133.156
            nova-novnc-proxy: 198.101.133.156
            nova-xvpvnc-proxy: 198.101.133.156
            swift-proxy: 198.101.133.156
            config:
                198.101.133.154:
                    vrid: 10
                    network: public
                198.101.133.155:
                    vrid: 11
                    network: public
                198.101.133.156:
                    vrid: 12
                    network: public
        centos:
            mysql-db: 198.101.133.157
            rabbitmq-queue: 198.101.133.158
            cinder-api: 198.101.133.159
            glance-api: 198.101.133.159
            glance-registry: 198.101.133.159
            horizon-dash: 198.101.133.159
            horizon-dash_ssl: 198.101.133.159
            keystone-admin-api: 198.101.133.159
            keystone-internal-api: 198.101.133.159
            keystone-service-api: 198.101.133.159
            nova-api: 198.101.133.159
            nova-ec2-public: 198.101.133.159
            nova-novnc-proxy: 198.101.133.159
            nova-xvpvnc-proxy: 198.101.133.159
            swift-proxy: 198.101.133.159
            config:
                198.101.133.157:
                    vrid: 14
                    network: public
                198.101.133.158:
                    vrid: 15
                    network: public
                198.101.133.159:
                    vrid: 16
                    network: public
rcbops:
    compute:
        git:
            url: https://github.com/rcbops/chef-cookbooks.git
            branches:
                master:
                    tags:
                        - v4.2.0
                havana:
                    tags:
                        - v4.2.0
                grizzly:
                    tags:
                        - v4.1.3
                        - v4.1.2
                        - v4.1.1
                        - v4.1.0
                        - v4.0.0
                folsom:
                    tags:
                        - v3.0.0
                        - v3.0.1
                        - v3.1.0
        chefserver:
            run_list: []
        compute:
            run_list: ['role[single-compute]']
        ldap:
            run_list: ['role[qa-openldap]']
        controller1:
            run_list: ['role[ha-controller1]']
        controller2:
            run_list: ['role[ha-controller2]']
        cinder:
            run_list: ['role[cinder-all]']
        network:
            run_list: ['role[single-network-node]']
        tempest:
            run_list: ['recipe[tempest]']
        orchestration:
            run_list: ['role[heat-all]']
        networkmanager:
            run_list: ['role[quantum-network-manager]']
        metrics:
            controller:
                run_list: ['role[ceilometer-setup]',
                           'role[ceilometer-api]',
                           'role[ceilometer-central-agent]',
                           'role[ceilometer-collector]']
            compute:
                run_list: ['role[ceilometer-compute]']
    storage:
        git:
            url: https://github.com/rcbops-cookbooks/swift-private-cloud.git
            branches:
                master:
                    tags:
                        - v4.2.0
        chef_server:
            run_list: []
        controller1:
            run_list: ['role[spc-starter-controller]']
        proxy:
            run_list: ['role[spc-starter-proxy]']
        storage:
            run_list: ['role[spc-starter-storage]']
tests:
  tempest:
    dir: "/opt/tempest"
    test_map:
      glance:
        - image
        - compute/images
      nova:
        - compute
      keystone:
        - compute/admin
        - compute/security_groups
        - compute/test_authorization.py
        - identity
      neutron:
        -
      cinder:
        - compute/volumes
        - volume
      swift:
        - object_storage

swift:
    master_env_key: swift-private-cloud
    auto_build_rings: False
    disk: "sdb"
    disk_label: "sdb1"
    num_rings: 3
    part_power: 10
    replicas: 3
    min_part_hours: 1
    disk_weight: 1000
    builders:
        object:
            port: 6000
        container:
            port: 6001
        account:
            port: 6002

cinder:
    vg_name: vg_storage

provisioners:
  razor: chefrazorprovisioner
  openstack: chefopenstackprovisioner
  rackspace: chefrackspaceprovisioner

rackspace:
  run_list:
    - recipe[rcbops-qa]
  images:
    precise: Ubuntu 12.04 LTS (Precise Pangolin)
    centos: CentOS 6.4
  flavors:
    512MB: 512MB Standard Instance
    1GB: 1GB Standard Instance
    2GB: 2GB Standard Instance
    4GB: 4GB Standard Instance
    8GB: 8GB Standard Instance
    15GB: 15GB Standard Instance
    30GB: 30GB Standard Instance

neutron:
    auto_build_subnets: False
    centos:
        network_bridge_device: em2
        vip: 198.101.133.159
    precise:
        network_bridge_device: eth1
        vip: 198.101.133.156
