precise-default:
  product: compute
  name: default
  os: precise
  features:
    openssh: default
    monitoring: default
    mysql: default
    glance: cf
    nova: default
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
    tempest: default
  nodes:
    - [chefserver]
    - [controller, orchestration]
    - [compute]

centos-default:
  product: compute
  name: default
  os: centos
  features:
    openssh: default
    monitoring: default
    mysql: default
    glance: cf
    cinder: local
    nova: default
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
  nodes:
    - [chefserver]
    - [controller, orchestration]
    - [compute]

precise-ha:
  product: compute
  name: ha
  os: precise
  features:
    openssh: default
    monitoring: default
    mysql: default
    glance: cf
    nova: default
    neutron: neutron
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
    highavailability: default
  nodes:
    - [chefserver]
    - [controller, network, orchestration]
    - [controller, network]
    - [compute]

centos-ha:
  product: compute
  name: ha
  os: centos
  features:
    openssh: default
    monitoring: default
    mysql: default
    glance: cf
    nova: default
    neutron: neutron
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
    highavailability: default
  nodes:
    - [chefserver]
    - [controller, network, orchestration]
    - [controller, network]
    - [compute]

precise-ha-nova-net:
  product: compute
  name: ha
  os: precise
  features:
    openssh: default
    monitoring: default
    mysql: default
    glance: cf
    nova: default
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
    highavailability: default
  nodes:
    - [chefserver]
    - [controller, orchestration]
    - [controller]
    - [compute]
    - [compute]

centos-ha:
  product: compute
  name: ha
  os: centos
  features:
    openssh: default
    monitoring: default
    mysql: default
    glance: cf
    nova: default
    neutron: neutron
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
    highavailability: default
  nodes:
    - [chefserver]
    - [controller, network, orchestration]
    - [controller, network]
    - [compute]

precise-swift:
  product: storage
  name: swift
  os: precise
  features:
    openssh: default
    keystone: swift
    swift: rpcs
  nodes:
    - [chefserver, berkshelf]
    - [controller]
    - [proxy]
    - [proxy]
    - [storage]
    - [storage]
    - [storage]

centos-swift:
  product: storage
  name: swift
  os: centos
  features:
    openssh: default
    keystone: swift
    swift: rpcs
  nodes:
    - [chefserver, berkshelf]
    - [controller]
    - [proxy]
    - [proxy]
    - [storage]
    - [storage]
    - [storage]
