precise-default:
  product: compute
  name: default
  os: precise
  features:
    monitoring: default
    mysql: default
    glance: cf
    nova: default
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
  nodes:
    - [chefserver]
    - [controller, ceilometer]
    - [compute, ceilometer]

centos-default:
  product: compute
  name: default
  os: centos
  features:
    monitoring: default
    mysql: default
    glance: cf
    cinder: local
    nova: default
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
  nodes:
    - [chefserver]
    - [controller, ceilometer]
    - [compute, ceilometer]

precise-neutron:
  product: compute
  name: neutron
  os: precise
  features:
    monitoring: default
    mysql: default
    glance: default
    nova: default
    neutron: neutron
    horizon: default
    keystone: default
    osops: default
    osopsnetworks: default
  nodes:
    - [chefserver]
    - [controller, network, ceilometer]
    - [compute, network, ceilometer]

precise-swift:
  product: storage
  name: swift
  os: precise
  features:
    keystone: swift
    swift: rpcs
  nodes:
    - [chefserver, berkshelf]
    - [controller]
    - [proxy]
    - [proxy]
    - [storage]
    - [storage]
    - [storage]

centos-swift:
  product: storage
  name: swift
  os: centos
  features:
    keystone: swift
    swift: rpcs
  nodes:
    - [chefserver, berkshelf]
    - [controller]
    - [proxy]
    - [proxy]
    - [storage]
    - [storage]
    - [storage]
